#!/usr/bin/env python3
"""
AegisArchive - Bundle Integrity Verifier
Verifies bundled artifacts against a SHA-256 checksum manifest (fail-closed).

Manifest format (one entry per line):
    <sha256-hex>  <relative-path>

Blank lines and lines starting with '#' are ignored. Verification fails
closed: a missing manifest, a missing artifact, or any digest mismatch is
an error and produces a non-zero exit code.

Licensed under the Apache License, Version 2.0.
"""

import argparse
import hashlib
import os
import sys

CHUNK = 1024 * 1024


def sha256_of(path):
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(CHUNK), b""):
            digest.update(block)
    return digest.hexdigest()


def parse_manifest(manifest_path):
    entries = []
    with open(manifest_path, "r", encoding="utf-8") as fh:
        for line_no, line in enumerate(fh, 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            parts = stripped.split(None, 1)
            if len(parts) != 2:
                raise ValueError(f"{manifest_path}:{line_no}: malformed entry")
            entries.append((parts[0].lower(), parts[1].strip()))
    return entries


def generate_manifest(root, out_path):
    """Walk root and write a SHA-256 manifest; returns the entry count."""
    lines = [
        "# AegisArchive bundle integrity manifest (SHA-256)",
        "# Generated by: python3 cli/verify_bundle.py --generate --root <dir>",
        "",
    ]
    count = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            d for d in dirnames
            if d != ".git" and not d.startswith("__pycache__")
        ]
        for name in sorted(filenames):
            if name.startswith(".") or name.startswith("._"):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            if os.path.abspath(full) == os.path.abspath(out_path):
                continue
            lines.append(f"{sha256_of(full)}  {rel}")
            count += 1
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return count


def verify(manifest_path, root):
    """Verify all manifest entries under root. Returns exit code (0 = pass)."""
    if not os.path.isfile(manifest_path):
        print(f"[FAIL] Manifest not found: {manifest_path} (fail-closed)")
        return 1
    try:
        entries = parse_manifest(manifest_path)
    except ValueError as err:
        print(f"[FAIL] {err}")
        return 1
    if not entries:
        print("[WARN] Manifest contains no entries; nothing to verify.")
        return 0
    failures = 0
    for expected, rel in entries:
        full = os.path.join(root, rel)
        if not os.path.isfile(full):
            print(f"[FAIL] Missing artifact: {rel}")
            failures += 1
            continue
        actual = sha256_of(full)
        if actual != expected:
            print(f"[FAIL] Digest mismatch: {rel} (expected {expected}, got {actual})")
            failures += 1
        else:
            print(f"[OK]   {rel}")
    if failures:
        print(f"[FAIL] {failures} integrity failure(s).")
        return 1
    print(f"[PASS] {len(entries)} artifact(s) verified.")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Verify bundled artifacts against a SHA-256 manifest (fail-closed)."
    )
    parser.add_argument(
        "--manifest", default="CHECKSUMS.sha256",
        help="Path to the checksum manifest (default: CHECKSUMS.sha256)",
    )
    parser.add_argument(
        "--root", default=".",
        help="Root directory that manifest paths are relative to",
    )
    parser.add_argument(
        "--generate", action="store_true",
        help="(Re)generate the manifest from --root instead of verifying",
    )
    args = parser.parse_args(argv)
    if args.generate:
        count = generate_manifest(args.root, args.manifest)
        print(f"[OK] Wrote {count} entries to {args.manifest}")
        return 0
    return verify(args.manifest, args.root)


if __name__ == "__main__":
    sys.exit(main())
